env: "$ENV:local"

app:
  id: "$APP_ID:00000000-0000-0000-0000-000000000000"
  name: "$APP_NAME:cam-external-task"

server:
  host: 0.0.0.0
  port: 8080

camunda:
  url: "$CAM_API_REST:http://localhost:58080/engine-rest"

auth:
  url: "$AUTH_API_URL:http://localhost:18080"
  clientId: "$AUTH_CLIENT_ID:00000000-0000-0000-0000-000000000000"
  clientSecret: "$AUTH_CLIENT_SECRET:00000000-0000-0000-0000-000000000000"
  grantType: "$AUTH_GRANT_TYPE:client_credentials"
